### PR TITLE
Create karl

### PR DESCRIPTION
**Pull request by diamondgoldk**

### CODE REVIEW

**Comment by samccone** [comment]
I :heart: karl as much as anyone, but I am not sure we need Karl here since he is free to drop in whenever he wants :goat:

**Comment by notwaldorf** [comment]
I'm going to leave this open a little bit longer, just in case this was a mis-push and you want to fix it to add actual code, but in that unlikely event, I'll probably close it tomorrow :)

**Comment by arthurvr** [comment]
Let's close this ;)

**Comment by samccone** [comment]
but karl!

**Comment by arthurevans** [comment]
I don't think Karl is coming, @samccone.

**Comment by addyosmani** [comment]
It's been nice knowing you, Karl!

**Comment by diamondgoldk** [comment]
Me too as well! how are you ?

**Comment by samccone** [comment]
Hard to say how Karl is, I once heard a tale of Karl taking a trip across the ocean :ocean:  in his :hand:  hand crafted :hammer:  bumper boat :boat:, living on nothing but :fish:. It was on this trip when Karl first came to the realization :thought_balloon: that he was nothing but Karl, no matter how hard he tried he would always be Karl. 

When Karl arrived on the coast of the UK :gb: in was late in the :night_with_stars:  night and everyone was asleep :sleeping:  he was startled when he was greeted by a friendly BFG 


who picked him up and took him on another adventure. 

... That was the last that I heard of Karl though, so who knows how he is :grey_question:

**Comment by diamondgoldk** [comment]
Sure doing good . that a Nice story😂

**Pull request closed without merging**
