### PR TITLE
fix demo styles

### PR DESCRIPTION
**Pull request by gurpreetatwal**
fixes #60 

I've attached screenshots of the fixed demo page below.

#### Microsoft Edge 40.15063.0.0
edge
-----
#### Chrome 60.0.3112.101 (64-bit)
chrome
-----
#### Firefox 55.0.1 (64-bit)
ff
----
#### Vivaldi 1.11.917.39 (Stable channel) (64-bit)
vivaldi

cc: @e111077 

Also should I be cc'ing you on these PRs? If not, please do let me know, don't want to bug you unnecessarily.

### CODE REVIEW

**Comment by e111077** [comment]
It seems as if im the _de facto_ maintainer on the team for these sets of elements now so you're fine with the CCs

**Comment by gurpreetatwal** [comment]
Ah okay, gotcha. Just wanted to make sure because I was planning to work on migrating the expiration and email elements to 2.0.

**Comment by e111077** [comment]
That would be very much appreciated. The polymer summit is this week across the world for me so I may have a delayed response to your PRs

**Comment by gurpreetatwal** [comment]
No worries, safe travels!

I just had a quick question regarding how all the hybrid elements that have an `iron-input` in them. I understand why there need to be two different templates for v1 vs v2 as the `is` attribute was removed in v2. But rather than writing that logic in every child element couldn't `iron-input` v2 just always have a nested input element? That would remove the need for all of the complicated logic in the child elements and put the messy portion in one location.

**Pull request merged**
